# test
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    # outputs:
    #   build-status:
    #     description: Build status
    #     value: ${{ steps.step1.outputs}}
    steps:
      - id: step1
        run: npm ci && npm run build
  # build:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     run: echo ${{build-status}}
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ./test_server.sh
  #   Build:
  #     name: "Build"
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #       - run: npm ci && npm run build
  #   Test:
  #     name: "Test"
  #     runs-on: ubuntu-latest
  #       steps:
  #         - uses: actions/checkout@v2
  #         - run: npm ci && npm run build
