# test
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - id: step1
      - run: npm ci && npm run build
  Echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo output is ${{output1}}
