# test
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12.x
      - run: npm ci
      - run: npm run build
